[package]
name = "smart_home_socket_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
libloading = "0.8.0"
smart_home_socket = { path = "../smart_home_socket" }
